# Generated by Django 5.2.1 on 2025-06-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='discription',
            new_name='description',
        ),
    ]
